name: Build and Test Backend

on:
  push:
    branches:
      - backend

jobs:
  build:
    name: Build and Test Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install Dependencies
        run: npm install
      - name: Run Tests
        run: npm test
      - name: Build the Project
        run: npm run build
